#!/bin/bash

# YouTube API Setup Script for MAONO Videos
# This script helps you set up YouTube API credentials

echo "🎬 MAONO YouTube API Setup"
echo "=========================="

echo "📋 Step-by-step YouTube API setup:"
echo ""
echo "1. 🌐 Go to Google Developers Console:"
echo "   https://console.developers.google.com/"
echo ""
echo "2. 📝 Create a new project:"
echo "   - Click 'Create Project'"
echo "   - Name it 'MAONO Videos'"
echo "   - Click 'Create'"
echo ""
echo "3. 🔧 Enable YouTube Data API v3:"
echo "   - Go to 'APIs & Services' > 'Library'"
echo "   - Search for 'YouTube Data API v3'"
echo "   - Click on it and press 'Enable'"
echo ""
echo "4. 🔐 Set up OAuth consent screen:"
echo "   - Go to 'APIs & Services' > 'OAuth consent screen'"
echo "   - Choose 'External' user type"
echo "   - Fill in app name: 'MAONO Video Uploader'"
echo "   - Add your email as developer contact"
echo "   - Add your email as test user"
echo ""
echo "5. 🔑 Create OAuth 2.0 credentials:"
echo "   - Go to 'APIs & Services' > 'Credentials'"
echo "   - Click 'Create Credentials' > 'OAuth client ID'"
echo "   - Choose 'Web application'"
echo "   - Name: 'MAONO Uploader'"
echo "   - Authorized redirect URIs:"
echo "     http://localhost:8080/oauth2callback"
echo "     http://localhost:8080"
echo ""
echo "6. 💾 Download credentials:"
echo "   - Click 'Download JSON'"
echo "   - Save as 'client_secrets.json'"
echo "   - Place it in this project directory"
echo ""
echo "7. ✅ Test the setup:"
echo "   - Run: python3 scripts/youtube-uploader.py"
echo ""

echo "🎯 What you'll get:"
echo "- All 6 videos uploaded to YouTube as unlisted"
echo "- Video IDs for embedding in your site"
echo "- Professional titles and descriptions"
echo "- Proper tags for SEO"
echo ""

echo "📱 Next steps after setup:"
echo "1. Run the upload script"
echo "2. Copy the video IDs"
echo "3. Update your code with the IDs"
echo "4. Deploy and enjoy fast videos!"
echo ""

echo "🚀 Ready to start? Follow the steps above, then run:"
echo "   python3 scripts/youtube-uploader.py"
